name: pathway_importer
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - charset-normalizer=3.2.0
  - colorama=0.4.6
  - idna=3.4
  - intel-openmp=2023.2.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libhwloc=2.9.2
  - libiconv=1.17
  - liblapack=3.9.0
  - libsqlite=3.42.0
  - libxml2=2.11.5
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lxml=4.9.3
  - mkl=2022.1.0
  - numpy=1.25.2
  - openssl=3.1.2
  - pandas=2.0.3
  - pip=23.2.1
  - pthreads-win32=2.9.1
  - pysocks=1.7.1
  - python=3.10.12
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3
  - requests=2.31.0
  - setuptools=68.0.0
  - six=1.16.0
  - tbb=2021.10.0
  - tk=8.6.12
  - tqdm=4.66.1
  - tzdata=2023c
  - ucrt=10.0.22621.0
  - urllib3=2.0.4
  - vc=14.3
  - vc14_runtime=14.36.32532
  - vs2015_runtime=14.36.32532
  - wheel=0.41.1
  - win_inet_pton=1.1.0
  - xz=5.2.6
