name: pathway_importer
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - cryptography=38.0.4
  - icu=72.1
  - idna=3.4
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libgomp=13.1.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.23
  - libsqlite=3.42.0
  - libstdcxx-ng=13.1.0
  - libuuid=2.38.1
  - libxml2=2.11.5
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lxml=4.9.3
  - ncurses=6.4
  - numpy=1.25.2
  - openssl=3.1.2
  - pandas=2.0.3
  - pip=23.2.1
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.12
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3
  - readline=8.2
  - requests=2.28.1
  - setuptools=68.0.0
  - six=1.16.0
  - tk=8.6.12
  - tqdm=4.66.1
  - tzdata=2023c
  - urllib3=1.26.14
  - wheel=0.41.1
  - xz=5.2.6
